import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AnimatedBackground from "./components/AnimatedBackground";
import Footer from "./components/Footer";
import Navigation from "./components/Navigation";
import ScrollObserver from "./components/ScrollObserver";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "ShotsByVidz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://ik.imagekit.io" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link href="https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className={`min-h-screen text-neutral-100 bg-neutral-950 font-sans antialiased selection:bg-pink-500/30 ${inter.variable}`}>
        <AnimatedBackground />
        <ScrollObserver />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
