const images = [
  {
    id: 1,
    url: "/images/swindonView.jpg",
    title: "Swindon View",
    description: "A view of the city of Swindon.",
    tags: ["city", "view", "architecture"],
  },
  {
    id: 2,
    url: "/images/skyTam.jpg",
    title: "Sky Tam",
    description: "Tam in the sky during sunset.",
    tags: ["sunset", "sky", "nature"],
  },
  {
    id: 3,
    url: "/images/rainDropGlasses.jpg",
    title: "Raindrop Glasses",
    description: "Raindrops on a pair of glasses.",
    tags: ["raindrops", "glasses", "weather"],
  },
  {
    id: 4,
    url: "/images/railTesley.jpg",
    title: "Rail Tesley",
    description: "Railway tracks in a rural area.",
    tags: ["railway", "tracks", "rural"],
  },
  {
    id: 5,
    url: "/images/parrot.jpg",
    title: "Parrot",
    description: "A colorful parrot perched on a branch.",
    tags: ["parrot", "bird", "nature"],
  },
  {
    id: 6,
    url: "/images/mudMotoBike.png",
    title: "Mud Moto Bike",
    description: "A motocross bike in the mud.",
    tags: ["bike", "mud", "motocross"],
  },
  {
    id: 7,
    url: "/images/mask.png",
    title: "Mask",
    description: "A decorative mask.",
    tags: ["mask", "decor", "art"],
  },
  {
    id: 8,
    url: "/images/Leaf.jpg",
    title: "Leaf",
    description: "Close-up shot of a green leaf.",
    tags: ["leaf", "nature", "plants"],
  },
  {
    id: 9,
    url: "/images/junglePortait.jpg",
    title: "Jungle Portrait",
    description: "Portrait of a person in a jungle setting.",
    tags: ["portrait", "jungle", "nature"],
  },
  {
    id: 10,
    url: "images/jokerCard.jpg",
    title: "Joker Card",
    description: "A joker playing card.",
    tags: ["joker", "cards", "playing"],
  },
  {
    id: 11,
    url: "/images/cathedralPigeonPark.jpg",
    title: "Cathedral Pigeon Park",
    description: "Pigeons in a park near a cathedral.",
    tags: ["pigeon", "park", "cathedral"],
  },
  {
    id: 12,
    url: "/images/CatEyes.jpg",
    title: "Cat Eyes",
    description: "Close-up shot of a cat's eyes.",
    tags: ["cat", "eyes", "pets"],
  },
  {
    id: 13,
    url: "/images/bulbwater_.jpg",
    title: "Bulb Water",
    description: "A bulb filled with water.",
    tags: ["bulb", "water", "creative"],
  },
  {
    id: 14,
    url: "/images/BirminghamClock.png",
    title: "Birmingham Clock",
    description: "A clock tower in the city of Birmingham.",
    tags: ["clock", "city", "architecture"],
  },
  {
    id: 15,
    url: "/images/birdNest.jpg",
    title: "Bird Nest",
    description: "A close-up shot of a bird's nest with eggs.",
    tags: ["bird", "nest", "nature"],
  },
  {
    id: 16,
    url: "/images/bird.jpg",
    title: "Bird",
    description: "A colorful bird perched on a branch.",
    tags: ["bird", "nature", "animals"],
  },
  {
    id: 17,
    url: "/images/bee.jpg",
    title: "Bee",
    description: "A close-up shot of a bee on a flower.",
    tags: ["bee", "flower", "nature"],
  },
  {
    id: 18,
    url: "/images/beachChainLock.jpg",
    title: "Beach Chain Lock",
    description: "A lock hanging on a chain at the beach.",
    tags: ["beach", "lock", "ocean"],
  },

  {
    id: 19,
    url: "/images/aceCard.jpg",
    title: "Ace card",
    description: "Ace card with strobe light around it.",
    tags: ["ace", "cards", "deck"],
  },
];

export default images;
